-- ================================================================
-- MIGRATION GOJIKA : Tables principales
-- ================================================================

-- Table : Années académiques
CREATE TABLE public.annees_academiques (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  libelle TEXT NOT NULL, -- Ex: "2024-2025"
  date_debut DATE NOT NULL,
  date_fin DATE NOT NULL,
  is_active BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now(),
  created_by uuid REFERENCES public.profiles(id)
);

COMMENT ON TABLE public.annees_academiques IS 'Années académiques créées par RP';

-- Table : Semestres
CREATE TABLE public.semestres (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  annee_id BIGINT NOT NULL REFERENCES public.annees_academiques(id) ON DELETE CASCADE,
  numero INT NOT NULL CHECK (numero IN (1, 2)),
  date_debut DATE NOT NULL,
  date_fin DATE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

COMMENT ON TABLE public.semestres IS 'Semestres d''une année académique';

-- Table : Événements académiques
CREATE TABLE public.evenements_academiques (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  annee_id BIGINT NOT NULL REFERENCES public.annees_academiques(id) ON DELETE CASCADE,
  titre TEXT NOT NULL,
  description TEXT,
  date_debut DATE NOT NULL,
  date_fin DATE,
  type_evenement TEXT, -- 'rentree', 'examen', 'ferie', 'autre'
  groupe_cible TEXT, -- NULL = tous les groupes
  site public.site_enum NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  created_by uuid REFERENCES public.profiles(id)
);

COMMENT ON TABLE public.evenements_academiques IS 'Événements du calendrier académique';

-- Table : Catégories d'examens
CREATE TABLE public.categories_examens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  libelle TEXT NOT NULL UNIQUE, -- 'Contrôle', 'Teste', 'TD', 'Examen semestriel', 'Repêchage'
  description TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

COMMENT ON TABLE public.categories_examens IS 'Types d''évaluation (Contrôle, Examen, TD...)';

-- Insertion des catégories par défaut
INSERT INTO public.categories_examens (libelle, description) VALUES
  ('Contrôle', 'Contrôle continu'),
  ('Teste', 'Test de connaissance'),
  ('TD', 'Travaux dirigés'),
  ('Examen semestriel', 'Examen de fin de semestre'),
  ('Repêchage', 'Session de rattrapage'),
  ('Stage noté', 'Évaluation de stage')
ON CONFLICT (libelle) DO NOTHING;

-- Table : Matières par semestre
CREATE TABLE public.matieres_semestre (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  semestre_id BIGINT NOT NULL REFERENCES public.semestres(id) ON DELETE CASCADE,
  matiere_id BIGINT NOT NULL REFERENCES public.matieres(id) ON DELETE CASCADE,
  coefficient NUMERIC(3, 1) DEFAULT 1.0,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(semestre_id, matiere_id)
);

COMMENT ON TABLE public.matieres_semestre IS 'Association matière-semestre avec coefficient';

-- Table : Délégués de classe
CREATE TABLE public.delegues (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  etudiant_id BIGINT NOT NULL REFERENCES public.etudiants(id) ON DELETE CASCADE,
  groupe TEXT NOT NULL,
  annee_id BIGINT NOT NULL REFERENCES public.annees_academiques(id) ON DELETE CASCADE,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now(),
  created_by uuid REFERENCES public.profiles(id),
  UNIQUE(etudiant_id, annee_id)
);

COMMENT ON TABLE public.delegues IS 'Étudiants délégués de classe';

-- Table : Salles de classe
CREATE TABLE public.salles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nom TEXT NOT NULL,
  site public.site_enum NOT NULL,
  capacite INT,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(nom, site)
);

COMMENT ON TABLE public.salles IS 'Salles de classe par site';

-- Activer RLS
ALTER TABLE public.annees_academiques ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.semestres ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.evenements_academiques ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories_examens ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.matieres_semestre ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.delegues ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.salles ENABLE ROW LEVEL SECURITY;

-- Politiques RLS basiques (lecture pour tous authentifiés, écriture pour RP/Admin)
CREATE POLICY "Lecture pour tous authentifiés" ON public.annees_academiques FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "RP/Admin peuvent tout gérer" ON public.annees_academiques FOR ALL USING (get_my_role() IN ('admin', 'rp'));

CREATE POLICY "Lecture pour tous authentifiés" ON public.semestres FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "RP/Admin peuvent tout gérer" ON public.semestres FOR ALL USING (get_my_role() IN ('admin', 'rp'));

CREATE POLICY "Lecture pour tous authentifiés" ON public.evenements_academiques FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "RP/Admin peuvent tout gérer" ON public.evenements_academiques FOR ALL USING (get_my_role() IN ('admin', 'rp'));

CREATE POLICY "Lecture pour tous authentifiés" ON public.categories_examens FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Admin peut tout gérer" ON public.categories_examens FOR ALL USING (get_my_role() = 'admin');

CREATE POLICY "Lecture pour tous authentifiés" ON public.matieres_semestre FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "RP/Admin peuvent tout gérer" ON public.matieres_semestre FOR ALL USING (get_my_role() IN ('admin', 'rp'));

CREATE POLICY "Lecture pour tous authentifiés" ON public.delegues FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "RP/Admin peuvent tout gérer" ON public.delegues FOR ALL USING (get_my_role() IN ('admin', 'rp'));

CREATE POLICY "Lecture pour tous authentifiés" ON public.salles FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "RP/Admin peuvent tout gérer" ON public.salles FOR ALL USING (get_my_role() IN ('admin', 'rp'));