-- ================================================================
-- MIGRATION GOJIKA : Emploi du temps & Assiduité
-- ================================================================

-- Amélioration de la table emplois_du_temps existante
ALTER TABLE public.emplois_du_temps
  ADD COLUMN IF NOT EXISTS annee_id BIGINT REFERENCES public.annees_academiques(id) ON DELETE CASCADE,
  ADD COLUMN IF NOT EXISTS heure_debut TIME NOT NULL DEFAULT '08:00',
  ADD COLUMN IF NOT EXISTS heure_fin TIME NOT NULL DEFAULT '10:00';

COMMENT ON TABLE public.emplois_du_temps IS 'Grille d''emploi du temps par groupe (GOJIKA)';

-- Table : Séances (pour les absences enregistrées)
CREATE TABLE public.seances (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  emploi_id BIGINT NOT NULL REFERENCES public.emplois_du_temps(id) ON DELETE CASCADE,
  date_seance DATE NOT NULL,
  is_annulee BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now()
);

COMMENT ON TABLE public.seances IS 'Instance d''un cours à une date donnée';

-- Amélioration de la table absences existante
ALTER TABLE public.absences
  ADD COLUMN IF NOT EXISTS seance_id BIGINT REFERENCES public.seances(id) ON DELETE CASCADE,
  ADD COLUMN IF NOT EXISTS est_retard BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS enregistre_par_delegue BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS approuve_par_rp BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS approuve_le TIMESTAMPTZ;

COMMENT ON TABLE public.absences IS 'Journal des absences/retards (GOJIKA)';

-- Amélioration de la table justifications existante
ALTER TABLE public.justifications
  ADD COLUMN IF NOT EXISTS absence_ids BIGINT[]; -- Référence multiple absences

COMMENT ON TABLE public.justifications IS 'Demandes de justification d''absence avec pièces jointes (GOJIKA)';

-- RLS pour emplois_du_temps
CREATE POLICY "Tout utilisateur authentifié peut lire" ON public.emplois_du_temps FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "RP/Admin peuvent tout gérer" ON public.emplois_du_temps FOR ALL USING (get_my_role() IN ('admin', 'rp'));

-- RLS pour seances
CREATE POLICY "Tout utilisateur authentifié peut lire" ON public.seances FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "RP/Enseignant/Délégué peuvent créer" ON public.seances FOR INSERT WITH CHECK (
  get_my_role() IN ('admin', 'rp', 'enseignant') OR
  EXISTS (SELECT 1 FROM public.delegues WHERE etudiant_id = get_my_student_id() AND is_active = true)
);

-- RLS pour absences (mise à jour)
DROP POLICY IF EXISTS "Le personnel de site peut lire les absences" ON public.absences;
DROP POLICY IF EXISTS "Les RP/Enseignants peuvent saisir" ON public.absences;

CREATE POLICY "Lecture selon rôle" ON public.absences FOR SELECT USING (
  get_my_role() IN ('admin', 'rp', 'enseignant') OR
  etudiant_id = get_my_student_id() OR
  etudiant_id IN (SELECT get_my_children_ids())
);

CREATE POLICY "RP/Enseignant/Délégué peuvent enregistrer" ON public.absences FOR INSERT WITH CHECK (
  get_my_role() IN ('admin', 'rp', 'enseignant') OR
  EXISTS (SELECT 1 FROM public.delegues WHERE etudiant_id = get_my_student_id() AND is_active = true)
);

CREATE POLICY "RP peut tout modifier" ON public.absences FOR UPDATE USING (get_my_role() IN ('admin', 'rp'));

-- RLS pour justifications (mise à jour)
DROP POLICY IF EXISTS "Les étudiants peuvent soumettre" ON public.justifications;
DROP POLICY IF EXISTS "Les parents peuvent soumettre" ON public.justifications;
DROP POLICY IF EXISTS "RP peut voir et valider" ON public.justifications;

CREATE POLICY "Étudiant/Parent peuvent soumettre" ON public.justifications FOR INSERT WITH CHECK (
  soumis_par_user_id = auth.uid() AND
  (etudiant_id = get_my_student_id() OR etudiant_id IN (SELECT get_my_children_ids()))
);

CREATE POLICY "Lecture selon rôle" ON public.justifications FOR SELECT USING (
  get_my_role() IN ('admin', 'rp') OR
  etudiant_id = get_my_student_id() OR
  etudiant_id IN (SELECT get_my_children_ids())
);

CREATE POLICY "RP peut valider/refuser" ON public.justifications FOR UPDATE USING (get_my_role() IN ('admin', 'rp'));