-- Types pour les Rôles
CREATE TYPE public.role_enum AS ENUM (
  'admin',
  'controleur',
  'responsable',
  'accueil',
  'rp',
  'enseignant',
  'parent',
  'etudiant'
);

-- Types pour les Sites
CREATE TYPE public.site_enum AS ENUM (
  'T',
  'TO',
  'BO',
  'BI',
  'FULL'
);

-- Types pour les Statuts
CREATE TYPE public.statut_etudiant_enum AS ENUM (
  'Actif',
  'Accord Spécial',
  'Abandon'
);

--
CREATE TYPE public.statut_justification_enum AS ENUM (
  'en_attente',
  'validee',
  'refusee'
);

--
CREATE TYPE public.statut_publication_enum AS ENUM (
  'brouillon',
  'en_attente_validation',
  'publiee',
  'archivee'
);

-- Table des profils utilisateurs
CREATE TABLE public.profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  nom_complet TEXT,
  email TEXT UNIQUE,
  role public.role_enum NOT NULL,
  site_rattache public.site_enum NOT NULL,
  avatar_url TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);
COMMENT ON TABLE public.profiles IS 'Profils étendus pour tous les utilisateurs (Admin, Accueil, RP, Etudiants, etc.)';

-- Table centrale des étudiants
CREATE TABLE public.etudiants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_etudiant_genere TEXT UNIQUE, -- Ex: "1-25-T"
  nom TEXT NOT NULL,
  prenom TEXT,
  date_naissance DATE,
  email_contact TEXT UNIQUE, -- Crucial pour la création du compte GOJIKA
  telephone TEXT,
  photo_url TEXT,
  site public.site_enum NOT NULL,
  mention_module TEXT,
  niveau TEXT,
  groupe TEXT,
  departement TEXT,
  statut public.statut_etudiant_enum NOT NULL DEFAULT 'Actif',
  statut_maj_le TIMESTAMPTZ DEFAULT now(),
  date_inscription TIMESTAMPTZ DEFAULT now(),
  risk_score INT DEFAULT 0, -- Score de risque (0=vert, 100=rouge)
  gojika_account_linked uuid UNIQUE REFERENCES auth.users(id) ON DELETE SET NULL
);
COMMENT ON TABLE public.etudiants IS 'Table centrale des étudiants (REJISTRA & GOJIKA)';

-- Table des Reçus
CREATE TABLE public.recus (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_etudiant BIGINT REFERENCES public.etudiants(id) ON DELETE SET NULL, -- Null si "Autre Paiement"
  site public.site_enum NOT NULL,
  created_by_user_id uuid NOT NULL REFERENCES public.profiles(id),
  date_paiement TIMESTAMPTZ DEFAULT now(),
  n_recu_principal TEXT NOT NULL,
  montant_total NUMERIC(10, 2) NOT NULL,
  mode_paiement TEXT,
  ref_transaction TEXT
);
COMMENT ON TABLE public.recus IS 'Gère un reçu unique qui peut contenir plusieurs items de paiement';

-- Table des Lignes de Paiement
CREATE TABLE public.paiement_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_recu BIGINT NOT NULL REFERENCES public.recus(id) ON DELETE CASCADE,
  id_etudiant BIGINT REFERENCES public.etudiants(id) ON DELETE CASCADE, -- Dénormalisé pour jointures faciles
  motif TEXT NOT NULL,
  mois_de TEXT, -- Ex: "Mois 1"
  montant NUMERIC(10, 2) NOT NULL
);
COMMENT ON TABLE public.paiement_items IS 'Lignes de détail pour chaque reçu (un item par motif)';

-- Table des Matières
CREATE TABLE public.matieres (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nom TEXT NOT NULL,
  site public.site_enum NOT NULL,
  enseignant_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL
);
COMMENT ON TABLE public.matieres IS 'Liste des matières enseignées par site';

-- Table des Notes
CREATE TABLE public.notes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  etudiant_id BIGINT NOT NULL REFERENCES public.etudiants(id) ON DELETE CASCADE,
  matiere_id BIGINT NOT NULL REFERENCES public.matieres(id),
  note NUMERIC(5, 2) NOT NULL,
  coefficient NUMERIC(3, 1) DEFAULT 1,
  type TEXT NOT NULL, -- 'Contrôle continu', 'Examen', etc.
  date_saisie TIMESTAMPTZ DEFAULT now(),
  saisie_par_user_id uuid NOT NULL REFERENCES public.profiles(id)
);
COMMENT ON TABLE public.notes IS 'Notes des étudiants (GOJIKA)';

-- Table des Justifications
CREATE TABLE public.justifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  etudiant_id BIGINT NOT NULL REFERENCES public.etudiants(id) ON DELETE CASCADE,
  soumis_par_user_id uuid NOT NULL REFERENCES public.profiles(id), -- Etudiant ou Parent
  motif TEXT NOT NULL,
  fichier_url TEXT, -- Lien vers Supabase Storage
  status public.statut_justification_enum NOT NULL DEFAULT 'en_attente',
  date_soumission TIMESTAMPTZ DEFAULT now(),
  valide_par_user_id uuid REFERENCES public.profiles(id) -- RP qui valide/refuse
);
COMMENT ON TABLE public.justifications IS 'Demandes de justification d''absence (GOJIKA)';

-- Table des Absences
CREATE TABLE public.absences (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  etudiant_id BIGINT NOT NULL REFERENCES public.etudiants(id) ON DELETE CASCADE,
  date_absence DATE NOT NULL,
  matiere_id BIGINT REFERENCES public.matieres(id), -- Cours manqué
  saisie_par_user_id uuid NOT NULL REFERENCES public.profiles(id), -- RP ou Enseignant
  justification_id BIGINT REFERENCES public.justifications(id) ON DELETE SET NULL
);
COMMENT ON TABLE public.absences IS 'Journal des absences (GOJIKA)';

-- Table Emploi du Temps
CREATE TABLE public.emplois_du_temps (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  matiere_id BIGINT NOT NULL REFERENCES public.matieres(id),
  groupe TEXT NOT NULL,
  salle TEXT,
  jour_semaine INT NOT NULL CHECK (jour_semaine BETWEEN 0 AND 6),
  heure_debut TIME NOT NULL,
  heure_fin TIME NOT NULL,
  site public.site_enum NOT NULL
);
COMMENT ON TABLE public.emplois_du_temps IS 'Grille d''emploi du temps par groupe (GOJIKA)';

-- Table des Publications
CREATE TABLE public.publications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titre TEXT NOT NULL,
  contenu TEXT,
  auteur_id uuid NOT NULL REFERENCES public.profiles(id),
  status public.statut_publication_enum NOT NULL DEFAULT 'brouillon',
  site_cible public.site_enum NOT NULL,
  groupe_cible TEXT, -- Null si pour tout le site
  date_publication TIMESTAMPTZ DEFAULT now()
);
COMMENT ON TABLE public.publications IS 'Annonces et communiqués (GOJIKA)';

-- Table Lien Parents-Étudiants
CREATE TABLE public.parents_etudiants_link (
  parent_user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  etudiant_id BIGINT NOT NULL REFERENCES public.etudiants(id) ON DELETE CASCADE,
  PRIMARY KEY (parent_user_id, etudiant_id)
);
COMMENT ON TABLE public.parents_etudiants_link IS 'Table pivot liant Parents et Etudiants (GOJIKA)';

-- Table de Configuration
CREATE TABLE public.config_options (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  categorie TEXT NOT NULL, -- 'Site', 'Motifs', 'Niveau', etc.
  valeur TEXT NOT NULL,
  UNIQUE(categorie, valeur)
);
COMMENT ON TABLE public.config_options IS 'Configuration dynamique (listes déroulantes)';

-- Table d'Audit
CREATE TABLE public.audit_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  timestamp TIMESTAMPTZ DEFAULT now(),
  user_id uuid REFERENCES public.profiles(id),
  user_name TEXT, -- Dénormalisé pour lecture facile
  site public.site_enum,
  action TEXT, -- 'CREATE_ETUDIANT', 'UPDATE_STATUT', etc.
  details JSONB -- Stocke les anciennes et nouvelles valeurs
);
COMMENT ON TABLE public.audit_log IS 'Historique de toutes les actions sensibles';