-- ================================================================
-- MIGRATION GOJIKA : Publications & Communication
-- ================================================================

-- Amélioration de la table publications existante
ALTER TABLE public.publications
  ADD COLUMN IF NOT EXISTS type_publication TEXT DEFAULT 'communique', -- 'communique', 'contenu', 'rappel', 'urgent'
  ADD COLUMN IF NOT EXISTS lien_video TEXT,
  ADD COLUMN IF NOT EXISTS image_url TEXT,
  ADD COLUMN IF NOT EXISTS approuve_par_rp BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS approuve_le TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS valide_par uuid REFERENCES public.profiles(id);

COMMENT ON TABLE public.publications IS 'Annonces et communiqués (GOJIKA)';

-- Table : Mot de la semaine (Admin)
CREATE TABLE public.mot_semaine (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  texte TEXT NOT NULL,
  auteur TEXT,
  date_debut DATE NOT NULL,
  date_fin DATE NOT NULL,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now(),
  created_by uuid REFERENCES public.profiles(id)
);

COMMENT ON TABLE public.mot_semaine IS 'Citation hebdomadaire visible par tous (Admin)';

ALTER TABLE public.mot_semaine ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Tous peuvent lire le mot actif" ON public.mot_semaine FOR SELECT USING (is_active = true);
CREATE POLICY "Admin peut tout gérer" ON public.mot_semaine FOR ALL USING (get_my_role() = 'admin');

-- Table : Messages privés (Admin <-> Utilisateurs)
CREATE TABLE public.messages_prives (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  expediteur_id uuid NOT NULL REFERENCES public.profiles(id),
  destinataire_id uuid NOT NULL REFERENCES public.profiles(id),
  objet TEXT,
  contenu TEXT NOT NULL,
  lu BOOLEAN DEFAULT false,
  lu_le TIMESTAMPTZ,
  date_envoi TIMESTAMPTZ DEFAULT now()
);

COMMENT ON TABLE public.messages_prives IS 'Messagerie entre Admin et utilisateurs';

ALTER TABLE public.messages_prives ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Lecture pour expéditeur/destinataire" ON public.messages_prives FOR SELECT USING (
  expediteur_id = auth.uid() OR destinataire_id = auth.uid()
);

CREATE POLICY "Utilisateurs peuvent envoyer" ON public.messages_prives FOR INSERT WITH CHECK (
  expediteur_id = auth.uid()
);

CREATE POLICY "Destinataire peut marquer comme lu" ON public.messages_prives FOR UPDATE USING (
  destinataire_id = auth.uid()
) WITH CHECK (
  destinataire_id = auth.uid()
);

-- Table : Notifications système
CREATE TABLE public.notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES public.profiles(id),
  titre TEXT NOT NULL,
  message TEXT NOT NULL,
  type_notification TEXT NOT NULL, -- 'info', 'alerte', 'rappel', 'urgent'
  lien TEXT, -- Lien vers une page spécifique de l'app
  lu BOOLEAN DEFAULT false,
  lu_le TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now()
);

COMMENT ON TABLE public.notifications IS 'Notifications en temps réel pour utilisateurs';

ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Utilisateur voit ses notifications" ON public.notifications FOR SELECT USING (
  user_id = auth.uid()
);

CREATE POLICY "Utilisateur peut marquer comme lu" ON public.notifications FOR UPDATE USING (
  user_id = auth.uid()
) WITH CHECK (
  user_id = auth.uid()
);

CREATE POLICY "Admin/RP peuvent créer" ON public.notifications FOR INSERT WITH CHECK (
  get_my_role() IN ('admin', 'rp')
);

-- RLS pour publications (mise à jour)
DROP POLICY IF EXISTS "Publications publiques visibles" ON public.publications;
DROP POLICY IF EXISTS "RP/Enseignants peuvent créer" ON public.publications;

CREATE POLICY "Lecture selon rôle et cible" ON public.publications FOR SELECT USING (
  status = 'publiee' AND
  (
    get_my_role() IN ('admin', 'rp') OR
    (
      (site_cible = (SELECT site FROM public.etudiants WHERE id = get_my_student_id())) AND
      (groupe_cible IS NULL OR groupe_cible = (SELECT groupe FROM public.etudiants WHERE id = get_my_student_id()))
    )
  )
);

CREATE POLICY "RP/Enseignant/Responsable peuvent créer" ON public.publications FOR INSERT WITH CHECK (
  get_my_role() IN ('admin', 'rp', 'enseignant', 'responsable')
);

CREATE POLICY "RP peut valider/refuser" ON public.publications FOR UPDATE USING (
  get_my_role() IN ('admin', 'rp')
);

-- Fonction : Créer une notification pour tous les étudiants d'un groupe
CREATE OR REPLACE FUNCTION public.notifier_groupe(
  p_groupe TEXT,
  p_titre TEXT,
  p_message TEXT,
  p_type TEXT DEFAULT 'info'
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  INSERT INTO public.notifications (user_id, titre, message, type_notification)
  SELECT e.gojika_account_linked, p_titre, p_message, p_type
  FROM public.etudiants e
  WHERE e.groupe = p_groupe AND e.gojika_account_linked IS NOT NULL;
END;
$$;

GRANT EXECUTE ON FUNCTION public.notifier_groupe(TEXT, TEXT, TEXT, TEXT) TO authenticated;